version: '3.4'

services:
  cat:
    image: cat
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      NODE_ENV: production
      PORT: 3000
    depends_on: 
      - postgres
    ports:
      - "8080:3000"
  postgres: 
    image: postgres:latest
    ports: 
      - "35000:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
